name: app_usage
description: App usage plugin for Android only, which can be used to get the time spent by the user in each app.
version: 4.0.1
homepage: https://github.com/cph-cachet/flutter-plugins/blob/master/packages/app_usage

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dk.cachet.app_usage
        pluginClass: AppUsagePlugin
