name: light
description: Plugin for collecting data from the ambient light sensor on Android.
version: 4.1.1
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: dk.cachet.light
        pluginClass: LightPlugin
