name: notifications
description: A plugin for tracking notifications on the device. Works exclusively for Android.
version: 3.1.0
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/notifications

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
  plugin:
    platforms:
      android:
        package: dk.cachet.notifications
        pluginClass: NotificationsPlugin
      ios:
        pluginClass: NotificationsPlugin
