name: air_quality
description: Air quality index from the World's Air Quality Index (WAQI) service.
version: 4.1.1
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/air_quality

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
